---
# REM: maunally install before using with
# $ ansible-galaxy install -r requirements.yml

- src: https://github.com/dheles/ansible-role-login-user
  name: login-user

- src: https://github.com/dheles/ansible-role-secure-ssh
  name: secure-ssh

- src: https://github.com/dheles/immport-galaxy-ansible-role
  name: immport

- src: https://github.com/dheles/r-ansible-role
  name: R
